language: node_js
node_js:
- '7'
cache:
  directories:
  - node_modules
install:
- npm install
notifications:
  email: false
addons:
  browserstack: 
    username: giuseppetufo1
    access_key: uyeBrmoT4yiC6WZqtWE6
script:
- npm run travis
- codecov
